In [1]:
import numpy as np
import pandas as pd

In [32]:
ko_genes = pd.read_csv('KO_genes.csv', index_col = 0)
blocking_ab_genes = pd.read_csv('blocking_ab_genes.csv', index_col = 0)

In [26]:
ko_genes

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,gene_name
Klf6,16781.088719,1.223238,0.333358,3.669446,2.430770e-04,6.225440e-04,Klf6
Ccnd2,4642.559869,-1.021800,0.162677,-6.281155,3.360664e-10,3.847331e-09,Ccnd2
Trim25,2381.403876,0.631092,0.230589,2.736871,6.202659e-03,1.040871e-02,Trim25
Scpep1,3538.981778,1.052169,0.243994,4.312270,1.615867e-05,6.366350e-05,Scpep1
Comt,1852.967721,0.563401,0.074239,7.589023,3.223254e-14,6.325380e-13,Comt
...,...,...,...,...,...,...,...
Cmtm4,3466.397502,-0.661285,0.181516,-3.643114,2.693592e-04,6.752608e-04,Cmtm4
Bin2,3474.901025,1.491467,0.137494,10.847502,2.049493e-27,2.036931e-25,Bin2
Sowahc,2322.954477,0.398533,0.107847,3.695360,2.195755e-04,5.704150e-04,Sowahc
Kctd12,19509.399554,0.928905,0.160850,5.774990,7.695764e-09,6.892630e-08,Kctd12
Samd4b,2039.270774,-0.426742,0.090834,-4.698023,2.626923e-06,1.342214e-05,Samd4b

In [27]:
blocking_ab_genes

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,gene_name
Gnai3,2779.416480,0.239001,0.090280,2.647334,0.008113,0.016684,Gnai3
Cav2,957.888809,-0.219906,0.107369,-2.048140,0.040546,0.065258,Cav2
Klf6,18865.068463,0.706029,0.196192,3.598661,0.000320,0.001456,Klf6
Cox5a,1013.842209,-0.458198,0.143207,-3.199547,0.001376,0.004196,Cox5a
Fer,895.478255,0.322992,0.080282,4.023200,0.000057,0.000414,Fer
...,...,...,...,...,...,...,...
Ndufb1,594.608831,-0.562631,0.179402,-3.136142,0.001712,0.004867,Ndufb1
Riok2,603.973760,0.263593,0.082153,3.208547,0.001334,0.004096,Riok2
A630089N07Rik,249.330292,-0.383353,0.174093,-2.201996,0.027666,0.046655,A630089N07Rik
Gm7072,474.885438,0.416931,0.216105,1.929294,0.053694,0.083119,Gm7072
Tmem223,229.311282,-0.501102,0.194857,-2.571640,0.010122,0.019984,Tmem223

In [33]:
blocking_ab_genes = blocking_ab_genes.add_suffix('_blocking_ab')
ko_genes = ko_genes.add_suffix('_ko')

In [35]:
blocking_ab_genes.join(ko_genes).dropna().to_csv('sig_gene_overlap.csv')